name: ropes
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  linter:
    path: ../linter
  test: ^1.16.0
