name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_call:

jobs:
  unit-test-coverage:
    if: ${{ !github.event.pull_request.draft }}

    runs-on: "ubuntu-latest"

    # Uncomment to run on the GitHub server
    # runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: test-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.3.10"
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: run tests
        run: |
          flutter --version
          dart pub global activate melos
          melos bootstrap
          melos get
          melos analyze
          melos test
